CREATE TABLE IF NOT EXISTS school (
	id SERIAL PRIMARY KEY NOT NULL,
	name CHARACTER VARYING(255) NOT NULL,
	UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS class (
	id SERIAL PRIMARY KEY NOT NULL,
	name CHARACTER VARYING(255) NOT NULL,
	school_id INTEGER NOT NULL,
	UNIQUE (name),
	FOREIGN KEY (school_id) REFERENCES school (id)
);4

CREATE TABLE IF NOT EXISTS note (
	id SERIAL PRIMARY KEY NOT NULL,
	name CHARACTER VARYING(255) NOT NULL,
    description TEXT NOT NULL,
    link TEXT NOT NULL,
	year_id INTEGER NOT NULL,
	FOREIGN KEY (year_id) REFERENCES year (id)
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS year (
	id SERIAL PRIMARY KEY NOT NULL,
	name CHARACTER VARYING(255) NOT NULL,
	class_id INTEGER NOT NULL,
	FOREIGN KEY (class_id) REFERENCES class (id)
);

CREATE TABLE IF NOT EXISTS comment (
	id SERIAL PRIMARY KEY NOT NULL,
    text TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id),
    note_id INTEGER NOT NULL,
	FOREIGN KEY (note_id) REFERENCES note (id)
);
